#ARDUINO_DIR            = arduino
TARGET                 = sketch1.pde
#ARDUINO_LIBS           = arduino/libraries/
#MCU                    = atmega32u4
#F_CPU                  = 16000000
ARDUINO_PORT           = /dev/ttyACM0
#AVRDUDE_ARD_BAUDRATE   = 115200
#AVRDUDE_ARD_PROGRAMMER = arduino

BOARD_TAG    		= leonardo

#include arduino/Arduino.mk



#   ARDUINO_DIR   = arduino
#   ARDMK_DIR     = /usr
#   AVR_TOOLS_DIR = /usr


   ARDUINO_DIR   = Arduino
   ARDMK_DIR     = ~/projects/arduino/Arduino-Makefile
   AVR_TOOLS_DIR = /usr

#include arduino/libraries/PinChangeInt/PinChangeInt.h

include ~/projects/arduino/Arduino-Makefile/arduino-mk/Arduino.mk
